# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: warning
  logs:
    custom_components.green_energy: debug
    custom_components.hacs: debug
    aiogithubapi: debug

sensor:
  - platform: time_date
    display_options:
      - 'date_time'

green_energy:
  green_energy_api_url: http://mock-api:4000
