version: "3.9"

services:
  homeassistant:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: homeassistant-awattar
    cap_add:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE
    ports:
      - "8123:8123"
    volumes:
      - ./custom_components/smartenergy_awattar:/config/custom_components/smartenergy_awattar
      - ./.storage:/config/.storage
